# Generated by Django 5.2.5 on 2026-06-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=150)),
                ('support_email', models.EmailField(max_length=254)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('timezone', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'system_settings',
            },
        ),
    ]
